### ISSUE TITLE
[1.12.2] ver.-2.0.1.1 The problem with the destruction of blocks of weapons

### ISSUE THREAD

**Issue by TheTestMod** [pWn3d1337/Techguns2#10]
Many experiments were carried out and the following was established:
(Testing was carried out only with TechGuns)
1 - At the first approach to the world, the blocks are destroyed by a rocket launcher.
2 - When re-entering the world, is not destroyed
3 - It does not matter whether the shots were fired at the first approach to the world.
Forge - 2604
Thank you in advance for your cooperation ;)

**Comment by pWn3d1337** [comment]
You switched the safemode on and off, there is a keybind for it and a button in the Techguns UI. The Red or Green symbol in the right corner indicates if you are in safe mode or not. In safe mode no gun does damage to the world.

**Comment by TheTestMod** [comment]
Thanks :)
