### ISSUE TITLE
Techguns crash of Oreclusterscanner

### ISSUE THREAD

**Issue by Y33tworm** [pWn3d1337/Techguns2#102]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: techguns/items/OreClusterScanner

**Comment by pWn3d1337** [comment]
That happens in 1.7 when you don't have installed the required mods (cofhlib & chisel)

**Comment by Y33tworm** [comment]
Ok, I will install Cofhlib and chisel thanks! (Sorry for the later reply)
