### ISSUE TITLE
Turret inventory filtering

### ISSUE THREAD

**Issue by xenoflot** [pWn3d1337/Techguns2#103]
Hi,

Playing with v1.12.2-2.0.11 in Wasted 1.1.4

I set up some Thermal Expansion itemducts to route empty cells out of turrets and into a charging station and back again. I found some empty cells in the left side inventory so I'm guessing that the turrets aren't filtering for valid inputs.

For giggles, I tested and was able to pipe some zombie flesh into a turret too :P

Cheers

**Comment by pWn3d1337** [comment]
This isn't really an issue. Just filter with pipes.

**Comment by xenoflot** [comment]
Fair enough. Thanks for the reply.
