### ISSUE TITLE
[Bug] Shooting and Reloading sounds

### ISSUE THREAD

**Issue by triffman33** [pWn3d1337/Techguns2#104]
Sound of shooting and reloading is higher on the left side than right side when standing completely still.

**Comment by triffman33** [comment]
Anything on this issue?

**Comment by pWn3d1337** [comment]
Can't reproduce the problem

**Comment by triffman33** [comment]
https://www.youtube.com/watch?v=2w-USbxpZaE&

The first two weapons you should be able to hear are a lot louder on the left side than the right but the third is what i imagine the others should also do.

**Comment by Thedudewiththefood** [comment]
According to my Game Output, the sounds for the Cyber Demon Blaster reloading and the Jetpack are missing.

Take a look: info
[20:38:20] [Client thread/WARN]: Missing sound for event: techguns:guns.cyberdemonblasterreload
20:38:20
game
info
[20:38:20] [Client thread/WARN]: Missing sound for event: techguns:jetpack.end
