### ISSUE TITLE
Some bugs in TG 2.0.2.0

### ISSUE THREAD

**Issue by VioletWyvern** [pWn3d1337/Techguns2#107]
1. Missing AS50 high explosion round's magazine crafting recipe,  You cannot loading these rounds into the empty AS50 magazine...

2. High Velocity rockets cannot using in the upgraded launchers **(Both in Guided Missile-Launcher and Grim Reaper)**, I know the nuclear warhead can only been used in rocket launcher is for the balance, But High Velocity rockets should also used in other upgraded launchers as well...

**Comment by pWn3d1337** [comment]
1. is a bug
2. is not implemented yet.

**Comment by pWn3d1337** [comment]
both issues fixed in https://github.com/pWn3d1337/Techguns2/releases/tag/2.0.2.0_pre2.1
