### ISSUE TITLE
requst for code information

### ISSUE THREAD

**Issue by Heyo13579** [pWn3d1337/Techguns2#109]
you have alot of info to help with craft tweaker changes but i need the list of the physical armor values so that i can tweak them for my pack. if this code could be added to the craft tweaker page that would be great

**Comment by pWn3d1337** [comment]
All armor values are shown in the item tooltips. Currently I won't make a list because armor values are not final yet and I might make some adjustments when the next tier is added.

**Comment by pWn3d1337** [comment]
The armor materials can also be viewed in the source code: https://github.com/pWn3d1337/Techguns2/blob/master/src/main/java/techguns/TGArmors.java#L48-L76

All armor values are split between Helmet (25%), Chest (30%), Legs (25%), Boots (20%)

The code in this repository is for the newest version (https://github.com/pWn3d1337/Techguns2/releases) and newer than the curseforge version.

**Comment by Heyo13579** [comment]
thats actually exactly what i was looking for thank you!
