### ISSUE TITLE
I can't play this mod

### ISSUE THREAD

**Issue by Shark9oooo** [pWn3d1337/Techguns2#11]
When I download it and start up the game it will not load in

**Comment by pWn3d1337** [comment]
Need more information, version? crash log?

**Comment by Shark9oooo** [comment]
no crash log just load in but no tech guns version 1.12.2

**Comment by pWn3d1337** [comment]
If it doesn't start up you likely did not install it correctly, but without a crash log I can't help you. Maybe you forge version is too old?
