### ISSUE TITLE
not sure how to set up the crafttweaker file

### ISSUE THREAD

**Issue by Heyo13579** [pWn3d1337/Techguns2#110]
im unsure what the proper formatting is for the .zs file when changing armor values as i understand from the wiki its 

```
import mods.techguns.ArmorStats;
import mods.techguns.GunStats;

ArmorStats.setArmorStat("t1_combat_boots","SPEED",1.2);
ArmorStats.setMaterialArmorValue("T1_COMBAT","PHYSICAL",24.0, "PROJECTILE", 24.0);
```

but this is not working

am i formatting it incorrectly?

i also have MTRM installed could that be causing conflicts with adding another .zs file?

**Comment by pWn3d1337** [comment]
the first line looks correct, the second is wrong.. you need to call it once for each type;
ArmorStats.setMaterialArmorValue("T1_COMBAT","PHYSICAL",24.0);
ArmorStats.setMaterialArmorValue("T1_COMBAT","PROJECTILE", 24.0);

**Comment by Heyo13579** [comment]
i made the changes but still not seeing it be reflected in game, i am restarting the game after every change. the changes should be reflected on the armor piece correct?

**Comment by pWn3d1337** [comment]
What does your crafttweaker log say?

**Comment by Heyo13579** [comment]
[PREINITIALIZATION][CLIENT][INFO] Current loaders after merging: [[preinit]]
[PREINITIALIZATION][CLIENT][INFO] Loading scripts for loader with names [preinit]
[PREINITIALIZATION][CLIENT][INFO] [preinit | SIDE_CLIENT]: Skipping file {[0:crafttweaker]: MineTweakerRecipeMaker.zs} as we are currently loading with a different loader
[PREINITIALIZATION][CLIENT][INFO] Completed script loading in: 2ms
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Building registry
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Successfully built item registry
[INITIALIZATION][CLIENT][INFO] Current loaders after merging: [[preinit], [recipeevent | crafttweaker]]
[INITIALIZATION][CLIENT][INFO] Loading scripts for loader with names [crafttweaker | recipeevent]
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: MineTweakerRecipeMaker.zs}
[INITIALIZATION][CLIENT][INFO] Removing Metal Press Recipes for Titanium Aluminide Rod
[INITIALIZATION][CLIENT][INFO] Removing Metal Press Recipes for Titanium Iridium Alloy Rod
[INITIALIZATION][CLIENT][INFO] Completed script loading in: 208ms
[POSTINITIALIZATION][CLIENT][INFO] Removing Shaped recipes for <techguns:miningdrill>
[POSTINITIALIZATION][CLIENT][INFO] 0 removed
[POSTINITIALIZATION][CLIENT][INFO] Removing Shaped recipes for <randomthings:spectrekey>
[POSTINITIALIZATION][CLIENT][INFO] 1 removed
[POSTINITIALIZATION][CLIENT][INFO] Removing Shaped recipes for <rftools:builder>
[POSTINITIALIZATION][CLIENT][INFO] 1 removed
[POSTINITIALIZATION][CLIENT][INFO] Adding shapeless recipe for Soul Sand with name ct_shapeless-927620648
[POSTINITIALIZATION][CLIENT][INFO] Adding shapeless recipe for Heart Crystal Shard with name ct_shapeless-1587995499
[POSTINITIALIZATION][CLIENT][INFO] Adding shapeless recipe for Heart Dust with name ct_shapeless1345920273
[POSTINITIALIZATION][CLIENT][INFO] Adding shapeless recipe for Heart Crystal Shard with name ct_shapeless1334902716
[POSTINITIALIZATION][CLIENT][INFO] Adding shapeless recipe for Coal Nugget with name ct_shapeless1248531499
[POSTINITIALIZATION][CLIENT][INFO] Adding shapeless recipe for Tiny Coal with name ct_shapeless1602481580
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Emeradic Crystal Boots with name ct_shaped-1528926161
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Emeradic Crystal Chest with name ct_shaped536134752
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Emeradic Crystal Chest with name ct_shaped-1311498500
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Emeradic Crystal Helmet with name ct_shaped-112252238
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Emeradic Crystal Helmet with name ct_shaped-112252237
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Dark Helm with name ct_shaped-1022523459
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Dark Plate with name ct_shaped-286756896
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Dark Leggings with name ct_shaped-301039512
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Dark Boots with name ct_shaped502203090
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Quantum Storage Unit with name ct_shaped-726387254
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Full heart with name ct_shaped1032802531
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Excavate Modifier with name ct_shaped710041274
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Small Medical Kit with name ct_shaped1783766669
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Heart Dust with name ct_shaped-102555160
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Heart Container with name ct_shaped272282943
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Healer with name ct_shaped-348634418
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Large Medical kit with name ct_shaped-818432075
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Bedrock with name ct_shaped-57977901
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Spectre Key with name ct_shaped304417451
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Magical Snow Globe with name ct_shaped-1283399635
[POSTINITIALIZATION][CLIENT][INFO] Adding shaped recipe for Builder with name ct_shaped71992349
[SERVER_STARTED][CLIENT][INFO] Fixed the RecipeBook

**Comment by Heyo13579** [comment]
from what i can see its not reading the second .zs file

**Comment by Heyo13579** [comment]
i figured it out .... i named the file wrongly -_- i did .ZS instead of .zs and thats what cause it to not read apparently....

i do have one more question how does the material values i set correspond to ingame values? ie i set it physical to 20 and it gave each piece 4 in game

**Comment by pWn3d1337** [comment]
elemental sets the value for fire, ice, lightning and energy

**Comment by Heyo13579** [comment]
[TechGuns.txt](https://github.com/pWn3d1337/Techguns2/files/2998148/TechGuns.txt)
these are the values i found for all of the gear a lot of values are missing from them because i cant find them in the files of the mod, the above is written in the crafttweaker format so feel free to post it to your wiki

**Comment by pWn3d1337** [comment]
The values you set for a material are for all 4 pieces together. and the split for the 4 parts is (25%, for helmet+leggins, 30% for chest, 20% for boots)

**Comment by Heyo13579** [comment]
awsome that helps alot also what about the missing values? is there a default value listed for values not written? or are they written some where else? for example the t1_combat only has the physical attribute defined but nothing else yet in game the armor has a value for all atributes

**Comment by pWn3d1337** [comment]
Yes, there are default values. Physical and projectile are set to the armor value passed directly in the constructor:
public static TGArmorMaterial T1_COMBAT = new TGArmorMaterial("T1_COMBAT", 60<baseDurability, 0<Enchantability, 15.0f<armor, SoundEvents.ITEM_ARMOR_EQUIP_LEATHER,0.5f<toughness);

All other values besides radiation is set to 75% of the armor value by default. Radiation is 0.

**Comment by Heyo13579** [comment]
is the armor value and the physical value interchangeable?
