### ISSUE TITLE
Bugged particles

### ISSUE THREAD

**Issue by RoboTheMAN** [pWn3d1337/Techguns2#113]
![ezgif-4-60592ebb14b2](https://user-images.githubusercontent.com/23659870/55037212-61533100-4ff3-11e9-9115-cfb2df7fbd36.gif)
Whenever a shot is fired by any gun, the particle effect on the barrel and the resulting particles from bullets landing results in a conflict with water. This is even more apparent when using shaders with Optifine, when it just results in a black box with the image as a particle.

**Comment by pWn3d1337** [comment]
Without Optifine and shaders everything works fine. Optifine is often not compatible with mods.

**Comment by VioletWyvern** [comment]
Try to using the newest Forge and Optifine,  I'm using the latest version of Optifine and found no visual problems...
