### ISSUE TITLE
Bullets crashes the server when shooting on a mining dimension portal

### ISSUE THREAD

**Issue by InfinitexX** [pWn3d1337/Techguns2#114]
When a bullets touch the mining dimension portal from the Aroma1997s Dimensional World mod, it crashes the server. I don't really know if it comes from techguns or the mining dimension mod but it's really annoying. I attached a crash report to let you see more details about the crash.
[crash-2019-03-27_17.25.53-server.txt](https://github.com/pWn3d1337/Techguns2/files/3014412/crash-2019-03-27_17.25.53-server.txt)

**Comment by pWn3d1337** [comment]
doesn't look like techguns problem to me. The method that crashes is doBlockCollisions() which is a default minecraft method. EntityArrow also calls this method.

**Comment by InfinitexX** [comment]
Thanks, it was coming form Aroma1997s Dimensional World mod. I updated it and it now works.
