### ISSUE TITLE
World generation crash in newest versions

### ISSUE THREAD

**Issue by Supercarlover1** [pWn3d1337/Techguns2#119]
[crash-2019-04-06_22.40.27-server.txt](https://github.com/pWn3d1337/Techguns2/files/3051147/crash-2019-04-06_22.40.27-server.txt)
I've tried without and with Chisel and CTM, different versions of Forge, with the mod by itself.  Every time I try to load a world with the TechGuns mod, Minecraft crashes.  This didn't happen with alpha versions for 1.12.2, only the beta versions.

**Comment by pWn3d1337** [comment]
There is no direct reference to techguns in the stacktrace.

**Comment by MakkuroJoKeRGod** [comment]
@Supercarlover1 I am encountering the same issues. I got the exact same crash report as you, mind if you tell me the solution to this problem if you ever find it?
