### ISSUE TITLE
Can you remove the square thing when a gun shoots?

### ISSUE THREAD

**Issue by Ludoki** [pWn3d1337/Techguns2#121]

**Comment by pWn3d1337** [comment]
Please put a detailed description in the bug tracker, I think you are referring to this reddit post: https://www.reddit.com/r/feedthebeast/comments/bb05fg/is_there_any_way_to_remove_this_square_im_using/

I do not have such squares, do you have another mod that could cause this? Optifine, Shaders?

**Comment by AngelusQQ** [comment]
I get this too but only with shaders which would make sense

**Comment by VioletWyvern** [comment]
Same as #113 ,  Try to using the newest Forge and Optifine, I'm using the latest version of Optifine and found no visual problems...
