### ISSUE TITLE
Question: Do you accept models?

### ISSUE THREAD

**Issue by BlastaMasta** [pWn3d1337/Techguns2#123]
Hello there. My name is Blaster Master and I am a friend of Victor, the creator of the Vic's Modern Warfare mod. I make various models for him, like armor, props and guns, so I have a nice bit of experience with modeling in techne. I really like your mod ( Though I still think that VMW is better in the realism regard, no offense ) and I was wondering if you accept any models. I find making models fun, especially the one's that are easier to make, thus I am really interested in maybe making a few models for your cool mod. Just for fun

**Comment by pWn3d1337** [comment]
Yes of course, I could always need good models.
VMW has different goals than techguns, Techguns is survival based and has the goal to integrate into tech based packs and still feel minecrafty.

I can render techne/tabula models or .obj models.
