### ISSUE TITLE
[Request] Vivecraft and Techguns

### ISSUE THREAD

**Issue by apopanda** [pWn3d1337/Techguns2#127]
In Vivecraft, the Techguns mod seems completely broken; no 3D models are present for the mod (giant cube with black-purple texture instead), the guns don't shoot anything when trying to use them, the glider seems to not accept the input from free-move, like it should, and instead ignores everything.

Is there any hope for fixing the Vivecraft - Techguns integration? We have a tiny server with a few people with Vives and Pimaxes, who would love to play on it in VR, but with the mod being broken, it's kind of a dealbreaker for us.

**Comment by pWn3d1337** [comment]
Gun models broken means the ASM hack does not work. Guns not shooting likely means the mouse events are fucked up.

That's not an easy fix and I don't really have the time to delve into that as I don't have VR myself.

**Comment by apopanda** [comment]
That's a shame. I can help with the testing if you find time, and are willing to try it.
