### ISSUE TITLE
Entire game with mod crashes after shooting any weapon

### ISSUE THREAD

**Issue by LanayruRanger** [pWn3d1337/Techguns2#136]
Have the mod installed with all of the requisite and recommend mods and libraries. Also have Inventory Tweaks, JEI and NEI installed. Whenever I shoot one of the weapons sometimes I'll be able to shoot it once but always when I try to shoot a second time the game freezes and simply crashes to the desktop.

**Comment by pWn3d1337** [comment]
post the crash log please

**Comment by LanayruRanger** [comment]
[crash-2019-06-11_02.59.41-client.txt](https://github.com/pWn3d1337/Techguns2/files/3275127/crash-2019-06-11_02.59.41-client.txt)

**Comment by LanayruRanger** [comment]
Actually I deleted Albedo and it works! Sorry for bothering you!
