### ISSUE TITLE
Power Armor Functionality Request

### ISSUE THREAD

**Issue by Keyedrin** [pWn3d1337/Techguns2#137]
Would it be possible to add a config option to allow the Power Armor (and possibly other energy cell items like laser rifles) to be powered directly by RF rather than needing the energy cell as a middle man? I would like to be able to put the armor directly into the charging station from Immersive Engineering, as I am making a pack revolving heavily around the mod, and neither Energy Cells or Power Armor can be charged through its charging station.
I hope this will be possible without requiring a massive rewrite of code, but I am not sure.

**Comment by pWn3d1337** [comment]
> I hope this will be possible without requiring a massive rewrite of code

No
