### ISSUE TITLE
Crash From RenderAttackHelicopter while using Optfine

### ISSUE THREAD

**Issue by IchigoGames** [pWn3d1337/Techguns2#139]
i got this crash as i got near the ship that spawns the attack Helicopter i was using optfine i know not every mod dev supports optfine but i wish i could at least disable the helicopter as a temp fix but its not a option. 

mc 1.12.2 
forge 2838
techguns-1.12.2-2.0.1.2_1
OptiFine_1.12.2_HD_U_E3
[crash-2019-06-28_19.15.11-client.txt](https://github.com/pWn3d1337/Techguns2/files/3341219/crash-2019-06-28_19.15.11-client.txt)

**Comment by pWn3d1337** [comment]
It's an optifine problem, and no I can't add options to disable every single feature of the mod, this is too much work. Also other .obj models (grenade launcher) could crash too. Short story: Optifine is not supported and never will as long as it stays closed source.

**Comment by superhealing** [comment]
Same issues happen only solely server.
