### ISSUE TITLE
suggestion if possible

### ISSUE THREAD

**Issue by mattrix444** [pWn3d1337/Techguns2#143]
hi i love this mod to bits but i was wondering if there was any chance of adding a small config that allows us to make it so all the mobs in the mod can be immune to the sun. thanks :)

**Comment by pWn3d1337** [comment]
They were until people cried that it was too difficult.

**Comment by mattrix444** [comment]
Omg babies. Maybe a toggle of some sort would be cool if possible no probs
if not. Thanks
