### ISSUE TITLE
Chemical Laboratory hard to automate

### ISSUE THREAD

**Issue by ChlorineX** [pWn3d1337/Techguns2#145]
> most recipes requiring 2 items allow them to be swapped

However, some recipes are not swap-able, such as mekanism biofuel + gunpowder = creeper acid, they're very hard to automate, the gunpowder much be in the second input slot but if the gunpowder gets in early then the biofuel, it would be in the first slot, and the machine would refuse to receive biofuel (I use pipes in Thermal Dynamics). Is it possible to make all recipes to be swap-able? Or add a button to lock input slots just like what TE does?

**Comment by ChlorineX** [comment]
Also, if the biofuel is all consumed, but there is some remaining gunpowder in slot 2, I'm unable to add biofuel to slot 1. I have to take back the gunpowder, then put biofuel in slot 1, finally put gunpowder in slot 2 again.

**Comment by pWn3d1337** [comment]
Are you using the newest version of techguns?

**Comment by ChlorineX** [comment]
Yeah
