### ISSUE TITLE
Installing TechGuns and Mystical Mechanics causes 3D TechGuns items to lose their icons

### ISSUE THREAD

**Issue by Keyedrin** [pWn3d1337/Techguns2#149]
When Mystical Mechanics is installed alongside TechGuns, the icons of TechGuns weapons and armor with 3D models are turned into missing textures. The items retain their 3D model texture, it is only inventory icons that disappear. Items without 3D models retain their icons, as do blocks.
This occurs with just TechGuns and Mystical Mechanics installed, and with both on their current release versions.

I also reported this to Mystical Mechanics.

**Comment by pWn3d1337** [comment]
Very likely Mystical Mechanics contains some kind of coremodding that breaks Techguns ASM.

**Comment by DaedalusGame** [comment]
it does not

**Comment by DaedalusGame** [comment]
yeah ok, adding a label doesn't mean it's not a problem with your mod.

MM doesn't contain any kind of coremodding that would interfere with your ASM.

**Comment by Aeron216** [comment]
Very unfortunate
