### ISSUE TITLE
Weird "crash"?

### ISSUE THREAD

**Issue by darthvader45** [pWn3d1337/Techguns2#152]
Not sure if this is a crash, but for some reason my game closed out, turning my entire computer screen black for a split second.  Using 2.0.2.0-pre3.1 on 1.12.2.  Apparently it may be the latest version of Optifine, but I'm not sure.  Will try downgrading to a version I used when I didn't have the crash.

**Comment by pWn3d1337** [comment]
Optifine can always cause problems

**Comment by darthvader45** [comment]
Alright, seems reverting fixed the issue.  I'll just stay at this older version until things smooth out.  Though that may never happen.
