### ISSUE TITLE
Disable to spawn attack helicopter

### ISSUE THREAD

**Issue by ym1025** [pWn3d1337/Techguns2#153]
I have optifine,so I get to crash when I fire a grenade launcher and spawning attack helicopter.
I want to disable spawning attack heli . but I can't find config to disable spawning them.
How to disable to spawn attack heli?

**Comment by Erwins7th** [comment]
I know adding a config option may not be an easy thing but the helicopter issue is a game breaking one so i think you should add the option to disable it.

**Comment by ym1025** [comment]
Anyway,I disable to spawn all structures of techguns.

**Comment by AriaThePeryton** [comment]
Honestly needs to have a config option, I run a server that uses hardcore darkness, so, Optine is indeed needed.
So simply "Turn off optifine" isn't a solution.
