### ISSUE TITLE
[1.12.2] Crash when spawning a attack helicopter

### ISSUE THREAD

**Issue by LegendHunter** [pWn3d1337/Techguns2#155]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  CXLibraryCore (CXLibrary-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 9/3/19 8:01 AM
Description: Rendering entity in world

java.lang.ArrayIndexOutOfBoundsException: 5
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.processQuad(VertexLighterFlat.java:237)
	at net.minecraftforge.client.model.pipeline.QuadGatheringTransformer.put(QuadGatheringTransformer.java:66)
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad.pipe(UnpackedBakedQuad.java:78)
	at techguns.client.render.entities.npcs.RenderAttackHelicopter.renderBakedModel(RenderAttackHelicopter.java:153)
	at techguns.client.render.entities.npcs.RenderAttackHelicopter.doRender(RenderAttackHelicopter.java:103)
	at techguns.client.render.entities.npcs.RenderAttackHelicopter.func_76986_a(RenderAttackHelicopter.java:34)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:839)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1800)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.processQuad(VertexLighterFlat.java:237)
	at net.minecraftforge.client.model.pipeline.QuadGatheringTransformer.put(QuadGatheringTransformer.java:66)
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad.pipe(UnpackedBakedQuad.java:78)
	at techguns.client.render.entities.npcs.RenderAttackHelicopter.renderBakedModel(RenderAttackHelicopter.java:153)
	at techguns.client.render.entities.npcs.RenderAttackHelicopter.doRender(RenderAttackHelicopter.java:103)
	at techguns.client.render.entities.npcs.RenderAttackHelicopter.func_76986_a(RenderAttackHelicopter.java:34)

-- Entity being rendered --
Details:
	Entity Type: techguns:attackhelicopter (techguns.entities.npcs.AttackHelicopter)
	Entity ID: 1976
	Entity Name: Attack Helicopter
	Entity's Exact location: -199.14, 87.92, 180.03
	Entity's Block location: World: (-200,87,180), Chunk: (at 8,5,4 in -13,11; contains blocks -208,0,176 to -193,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: techguns.client.render.entities.npcs.RenderAttackHelicopter@808730a
	Location: 1.43,23.92,19.10 - World: (1,23,19), Chunk: (at 1,1,3 in 0,1; contains blocks 0,0,16 to 15,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: -69.375
	Delta: 0.5400152
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:839)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1800)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['LucasSport'/2474, l='MpServer', x=-200.57, y=64.00, z=160.93]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-158,64,194), Chunk: (at 2,4,2 in -10,12; contains blocks -160,0,192 to -145,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1052064 game time, 876938 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 95 total; [MoCEntityRoach['Roach'/2053, l='MpServer', x=-168.42, y=64.00, z=94.63], MoCEntityMouse['Mouse'/2054, l='MpServer', x=-166.52, y=65.00, z=113.62], MoCEntityMouse['Mouse'/2055, l='MpServer', x=-161.86, y=64.00, z=125.36], EntityPig['Pig'/1928, l='MpServer', x=-253.25, y=73.00, z=87.49], ZombieMiner['Zombie Miner'/1929, l='MpServer', x=-243.50, y=30.00, z=110.50], EntitySpider['Spider'/1930, l='MpServer', x=-252.50, y=25.00, z=115.50], ZombieFarmer['Zombie Farmer'/1931, l='MpServer', x=-254.50, y=26.00, z=131.50], MoCEntityMaggot['Maggot'/1932, l='MpServer', x=-254.69, y=64.00, z=177.88], MoCEntityPandaBear['PandaBear'/1933, l='MpServer', x=-247.98, y=67.00, z=223.90], MoCEntityBird['Bird'/2066, l='MpServer', x=-153.67, y=66.00, z=84.64], MoCEntityButterfly['ButterFly'/2067, l='MpServer', x=-150.74, y=63.00, z=107.45], MoCEntitySnake['Snake'/2068, l='MpServer', x=-156.92, y=64.00, z=143.04], EntityZombie['Zombie'/2069, l='MpServer', x=-151.29, y=40.00, z=217.54], MoCEntityBee['Bee'/2070, l='MpServer', x=-147.01, y=69.00, z=228.01], MoCEntityMouse['Mouse'/1956, l='MpServer', x=-237.24, y=7.00, z=179.85], ZombieFarmer['Zombie Farmer'/2084, l='MpServer', x=-128.44, y=54.00, z=132.19], ZombieMiner['Zombie Miner'/1957, l='MpServer', x=-230.50, y=22.00, z=176.50], EntityCreeper['Creeper'/2085, l='MpServer', x=-140.83, y=27.00, z=170.50], ZombieMiner['Zombie Miner'/1958, l='MpServer', x=-234.54, y=28.00, z=193.18], ZombieMiner['Zombie Miner'/2086, l='MpServer', x=-139.50, y=22.00, z=172.50], ZombieFarmer['Zombie Farmer'/1959, l='MpServer', x=-229.50, y=28.00, z=194.50], MoCEntityButterfly['ButterFly'/2087, l='MpServer', x=-134.67, y=64.00, z=175.05], MoCEntityBee['Bee'/1960, l='MpServer', x=-225.90, y=64.00, z=233.60], MoCEntityHorseMob['HorseMob'/2088, l='MpServer', x=-143.30, y=21.17, z=172.70], ZombieMiner['Zombie Miner'/2089, l='MpServer', x=-128.49, y=43.00, z=217.43], ZombieFarmer['Zombie Farmer'/2090, l='MpServer', x=-129.50, y=43.00, z=217.50], GCEntityClientPlayerMP['LucasSport'/2474, l='MpServer', x=-200.57, y=64.00, z=160.93], EntityCreeper['Creeper'/1842, l='MpServer', x=-274.21, y=16.00, z=114.49], MoCEntityFly['Fly'/2098, l='MpServer', x=-122.02, y=65.00, z=123.75], MoCEntityFishy['Fishy'/1844, l='MpServer', x=-275.42, y=62.10, z=118.22], MoCEntityFly['Fly'/2101, l='MpServer', x=-122.03, y=64.00, z=160.82], ZombieFarmer['Zombie Farmer'/1974, l='MpServer', x=-208.81, y=38.00, z=120.47], MoCEntityFirefly['Firefly'/1847, l='MpServer', x=-273.10, y=63.00, z=119.80], EntityItem['item.item.rottenFlesh'/1975, l='MpServer', x=-208.75, y=64.00, z=114.77], AttackHelicopter['Attack Helicopter'/1976, l='MpServer', x=-199.14, y=87.92, z=180.03], MoCEntityFishy['Fishy'/1849, l='MpServer', x=-270.35, y=61.85, z=129.74], MoCEntityStingRay['StingRay'/1851, l='MpServer', x=-278.15, y=58.59, z=127.90], MoCEntityGoat['Goat'/2107, l='MpServer', x=-121.44, y=69.48, z=217.39], MoCEntityGoldFish['GoldFish'/1852, l='MpServer', x=-276.21, y=61.88, z=131.16], MoCEntitySnake['Snake'/2108, l='MpServer', x=-126.60, y=67.00, z=239.22], MoCEntityGoldFish['GoldFish'/1853, l='MpServer', x=-274.55, y=62.10, z=130.44], MoCEntityKitty['Kitty'/2109, l='MpServer', x=-121.87, y=66.00, z=232.94], ZombieMiner['Zombie Miner'/1855, l='MpServer', x=-279.50, y=46.00, z=153.50], MoCEntityManderin['Manderin'/1856, l='MpServer', x=-272.42, y=62.00, z=143.94], MoCEntityDolphin['Dolphin'/1857, l='MpServer', x=-261.75, y=62.00, z=164.25], MoCEntityManderin['Manderin'/1860, l='MpServer', x=-272.24, y=62.30, z=169.15], MoCEntityFishy['Fishy'/1861, l='MpServer', x=-275.36, y=62.05, z=171.47], MoCEntityManderin['Manderin'/1862, l='MpServer', x=-276.64, y=61.38, z=171.04], MoCEntityAngelFish['AngelFish'/1863, l='MpServer', x=-278.45, y=61.71, z=172.03], MoCEntityFishy['Fishy'/1865, l='MpServer', x=-276.73, y=62.00, z=179.85], ZombieFarmer['Zombie Farmer'/1871, l='MpServer', x=-274.50, y=15.00, z=236.50], ZombieMiner['Zombie Miner'/2011, l='MpServer', x=-188.81, y=35.00, z=119.52], ZombieFarmer['Zombie Farmer'/2012, l='MpServer', x=-198.71, y=50.00, z=117.45], ZombieMiner['Zombie Miner'/1885, l='MpServer', x=-267.50, y=29.00, z=123.50], MoCEntityThrowableRock['entity.mocreatures:trock.name'/2013, l='MpServer', x=-202.09, y=65.00, z=123.57], MoCEntityManderin['Manderin'/1886, l='MpServer', x=-267.57, y=62.00, z=125.15], EntityCustomNpc['Div Archer'/2014, l='MpServer', x=-197.66, y=64.00, z=128.08], MoCEntityGoldFish['GoldFish'/1887, l='MpServer', x=-266.70, y=62.00, z=129.58], EntityCustomNpc['Div Paladin Knight'/2015, l='MpServer', x=-202.45, y=64.00, z=141.56], MoCEntityClownFish['ClownFish'/1888, l='MpServer', x=-263.35, y=61.63, z=137.43], EntityCustomNpc['Div Paladin Knight'/2016, l='MpServer', x=-205.58, y=64.00, z=142.48], MoCEntityAngelFish['AngelFish'/1889, l='MpServer', x=-270.65, y=62.06, z=135.67], EntityCustomNpc['Div Paladin Knight'/2017, l='MpServer', x=-200.50, y=64.00, z=140.50], MoCEntityAngelFish['AngelFish'/1890, l='MpServer', x=-271.19, y=62.04, z=137.05], EntityCustomNpc['Div Paladin Knight'/2018, l='MpServer', x=-197.75, y=64.00, z=142.41], MoCEntityStingRay['StingRay'/1891, l='MpServer', x=-261.60, y=60.00, z=140.71], EntityCustomNpc['Div Beserker'/2019, l='MpServer', x=-205.07, y=64.00, z=151.34], ZombieFarmer['Zombie Farmer'/1892, l='MpServer', x=-266.50, y=42.00, z=155.78], EntityCustomNpc['Div Beserker'/2020, l='MpServer', x=-200.73, y=64.00, z=157.25], EntitySkeleton['Skeleton'/1893, l='MpServer', x=-271.50, y=44.00, z=154.50], EntitySkeleton['Skeleton'/2021, l='MpServer', x=-195.48, y=41.00, z=191.71], ZombieFarmer['Zombie Farmer'/1894, l='MpServer', x=-260.30, y=46.00, z=147.70], EntitySkeleton['Skeleton'/1895, l='MpServer', x=-271.76, y=45.00, z=151.51], MoCEntityPiranha['Piranha'/1896, l='MpServer', x=-261.70, y=62.05, z=147.52], MoCEntityManderin['Manderin'/1897, l='MpServer', x=-266.06, y=62.28, z=145.16], MoCEntityPiranha['Piranha'/1898, l='MpServer', x=-259.50, y=60.93, z=149.50], MoCEntityPiranha['Piranha'/1899, l='MpServer', x=-260.76, y=61.88, z=147.60], MoCEntityClownFish['ClownFish'/1900, l='MpServer', x=-264.50, y=62.16, z=144.50], MoCEntityClownFish['ClownFish'/1901, l='MpServer', x=-268.30, y=62.39, z=151.42], MoCEntityGoldFish['GoldFish'/1902, l='MpServer', x=-269.56, y=61.78, z=157.81], MoCEntityGoldFish['GoldFish'/1903, l='MpServer', x=-268.13, y=61.76, z=158.38], ZombieMiner['Zombie Miner'/1904, l='MpServer', x=-262.52, y=43.00, z=160.78], MoCEntityFishy['Fishy'/1905, l='MpServer', x=-260.57, y=62.00, z=163.64], MoCEntityAngelFish['AngelFish'/1906, l='MpServer', x=-269.98, y=61.74, z=167.80], MoCEntityAngelFish['AngelFish'/1907, l='MpServer', x=-263.50, y=61.21, z=160.50], MoCEntityGoldFish['GoldFish'/1908, l='MpServer', x=-262.57, y=61.94, z=160.72], ZombieMiner['Zombie Miner'/1909, l='MpServer', x=-261.50, y=24.00, z=176.50], MoCEntitySnail['Snail'/1910, l='MpServer', x=-258.42, y=64.00, z=191.16], MoCEntityMaggot['Maggot'/1911, l='MpServer', x=-256.20, y=64.00, z=178.41], EntityItem['item.item.string'/1912, l='MpServer', x=-257.24, y=48.00, z=211.88], MoCEntityMouse['Mouse'/1913, l='MpServer', x=-257.85, y=69.00, z=221.85], EntityCow['Cow'/2041, l='MpServer', x=-183.45, y=66.00, z=83.19], ZombieMiner['Zombie Miner'/2042, l='MpServer', x=-185.50, y=47.00, z=122.50], EntityItem['item.item.techguns.riflerounds'/2043, l='MpServer', x=-177.92, y=64.00, z=142.36], EntityItem['item.item.techguns.riflerounds'/2044, l='MpServer', x=-176.98, y=64.00, z=153.56]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1037494256 bytes (989 MB) / 3424124928 bytes (3265 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2844 Optifine OptiFine_1.12.2_HD_U_E3 52 mods loaded, 52 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version           | Source                                           | Signature                                |
	|:------ |:-------------------- |:----------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2            | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp                  | 9.42              | minecraft.jar                                    | None                                     |
	| LCHIJA | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2844.jar                    | None                                     |
	| LCHIJA | forge                | 14.23.5.2844      | forge-1.12.2-14.23.5.2844.jar                    | None                                     |
	| LCHIJA | micdoodlecore        |                   | minecraft.jar                                    | None                                     |
	| LCHIJA | techguns_core        | 1.12.2-1.0        | minecraft.jar                                    | None                                     |
	| LCHIJA | securitycraft        | v1.8.12           | [1.12.2]+SecurityCraft+v1.8.12.jar               | None                                     |
	| LCHIJA | cxlibrary            | 1.6.1             | CXLibrary-1.12.2.jar                             | None                                     |
	| LCHIJA | advinv               | 1.4.2             | advInv-1.12.1-1.4.2.jar                          | None                                     |
	| LCHIJA | thedragonlib         | 1.12.2-5.3.0      | thedragonlib-1.12.2-5.3.0.jar                    | None                                     |
	| LCHIJA | armorplus            | 1.12.2-11.24.0.60 | armorplus-1.12.2-11.24.0.60.jar                  | None                                     |
	| LCHIJA | betterthanmending    | 1.1.1             | Better-Than-Mending-Mod-1.12.2.jar               | None                                     |
	| LCHIJA | cfm                  | 6.3.0             | cfm-6.3.0-mc1.12.2.jar                           | None                                     |
	| LCHIJA | ctm                  | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                        | None                                     |
	| LCHIJA | chisel               | MC1.12.2-0.2.0.31 | Chisel-Mod-1.12.2.jar                            | None                                     |
	| LCHIJA | subcommonlib         | 1.2.0.1           | subcommonlib-sublib-1.12.2-1.2.0.4.jar           | None                                     |
	| LCHIJA | rpginventory         | 1.12.2            | Rpg-Inventory-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | beastmaster          | $version          | Class-Armor-Mod-Beast-Master-1.12.2.jar          | None                                     |
	| LCHIJA | bma_addon            | 1.11.2 4.0.3.0    | Class-Armor-Mod-Berserker-Mage-Archer-1.12.2.jar | None                                     |
	| LCHIJA | umbralux             | 1.12.2            | Class-Armor-Mod-Necromancer-Paladin-1.12.2.jar   | None                                     |
	| LCHIJA | classiccombat        | 1.0.1             | Classic-Combat-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | codechickenlib       | 3.2.3.357         | CodeChickenLib-1.12.2-3.2.3.357-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux         | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | cofhcore             | 4.6.2             | CoFHCore-1.12.2.jar                              | None                                     |
	| LCHIJA | customspawner        | 3.11.4            | CustomMobSpawner-3.11.4.jar                      | None                                     |
	| LCHIJA | customnpcs           | 1.12              | CustomNPCs_1.12.2-30May19snapshot.jar            | None                                     |
	| LCHIJA | cyclopscore          | 1.5.0             | CyclopsCore-1.12.2-1.5.0.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | dmonsters            | 1.7               | Deadly-Monsters-Mod-1.12.2.jar                   | None                                     |
	| LCHIJA | doggytalents         | 1.15.0.5          | Doggy-Talents-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | mocreatures          | 12.0.5            | DrZharks MoCreatures Mod-12.0.5.jar              | None                                     |
	| LCHIJA | enchxchg             | 1.0.6             | Enchantments-Exchanger-Mod-1.12.2.jar            | None                                     |
	| LCHIJA | everlastingabilities | 1.5.1             | Everlasting Abilities Mod 1.12.2.jar             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | galacticraftcore     | 4.0.1.181         | GalacticraftCore-1.12.2-4.0.1.181.jar            | None                                     |
	| LCHIJA | galacticraftplanets  | 4.0.1.181         | Galacticraft-Planets-1.12.2-4.0.1.181.jar        | None                                     |
	| LCHIJA | grapplemod           | 1.12.2-v11.1      | grapplemod-v11.1-1.12.2.jar                      | None                                     |
	| LCHIJA | ironbackpacks        | 1.12.2-3.0.8-12   | IronBackpacks-1.12.2-3.0.8-12.jar                | None                                     |
	| LCHIJA | jei                  | 4.15.0.287        | jei_1.12.2-4.15.0.287.jar                        | None                                     |
	| LCHIJA | kaishiweapons        | v2018.01          | Kaishis-Weapon-Pack-Mod-1.12.2.jar               | None                                     |
	| LCHIJA | levelup2             | ${version}        | Level-Up-Mod-1.12.2.jar                          | None                                     |
	| LCHIJA | morefurnaces         | 1.10.5            | More-Furnaces-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | moreplayermodels     | 1.12.2            | More-Player-Models-Mod-1.12.2.jar                | None                                     |
	| LCHIJA | nei                  | 2.4.3             | NotEnoughItems-1.12.2-2.4.3.245-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ore_biome            | 1.0.1             | Ore-Biome-Mod-1.12.2.jar                         | None                                     |
	| LCHIJA | progressivebosses    | 1.5.1             | Progressive-Bosses-Mod-1.12.2.jar                | None                                     |
	| LCHIJA | randomenchantments   | @VERSION@         | Random-Enchants-Mod-1.12.2.jar                   | None                                     |
	| LCHIJA | reforged             | 0.7.5             | Reforged-Mod-1.12.jar                            | None                                     |
	| LCHIJA | somanyenchantments   | 0.4.4             | So+Many+Enchantments+V0.4.4.jar                  | None                                     |
	| LCHIJA | techguns             | 2.0.2.0           | techguns-1.12.2-2.0.2.0_pre3.1.jar               | None                                     |
	| LCHIJA | trashslot            | 8.4.10            | TrashSlot_1.12.2-8.4.10.jar                      | None                                     |
	| LCHIJA | variedcommodities    | 1.12.2            | VariedCommodities_1.12.2(15may18.jar             | None                                     |
	| LCHIJA | worldedit            | 6.1.10-SNAPSHOT   | WorldEdit-1.12.2.jar                             | None                                     |
	| LCHIJA | xlfoodmod            | 1.12.2-1.9.2      | XL-Food-Mod-1.12.2.jar                           | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
CXLibraryCore (CXLibrary-1.12.2.jar)
  cubex2.cxlibrary.CoreModTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
  techguns.core.TechgunsASMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 417.71' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2844
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 417.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A6-3600 APU with Radeon(tm) HD Graphics

**Comment by pWn3d1337** [comment]
Remove optifine

**Comment by DarkShyMW** [comment]
@pWn3d1337 if i cant remove optifine, what i should to do?
