### ISSUE TITLE
Techgun2 and Albedo crash report

### ISSUE THREAD

**Issue by TPC25** [pWn3d1337/Techguns2#156]
Minecraft Version: 1.12.2
Forge Version: 1.12.2 - 14.23.5.2838
Albedo Version: 1.12.2 - 1.1.0
Techgun2 Version: 1.12.2 - 2.0.2.0_pre3.1

Crash log: https://pastebin.com/cc7hEkBm

I read up on the techgun wiki and saw where it said this mod supports Albedo and decided to download and try albedo with it cause I wanted to see how the lighting would look. Started a test world in creative to test it out, pulled out the minigun (my favorite) and as soon as I fired, the game crash with the the above crash log. I try it again and got the same result. Is this crash log already in the works of being fix?

**Comment by pWn3d1337** [comment]
Albedo changed it's api so mods built for an older albedo version don't work. The old 0.1.3 version of albedo works with techguns. I updated the mod already locally, until there is a new version of TG, use the old albedo

**Comment by TPC25** [comment]
Oooh ok. The old version is working, thank you, looking forward to the new update of TG, keep up the great work. :)
