### ISSUE TITLE
Turret can't be powered

### ISSUE THREAD

**Issue by colin15523** [pWn3d1337/Techguns2#161]
I have been researching for almost 3 hours, and as far as I can tell there is NOTHING that generates FE energy that is compatible with turret, I tested MC Flux and Energy Converters. They don't work even though they say they generate FE energy.
since you guys made the mod, can you find a mod that works, or at least re-add  the config for power requirement, as it is not there in the version I'm using, 1.12.2-2.0.1.2

**Comment by colin15523** [comment]
In other words I think that using a energy type that either isn't already provided(like redstone), isn't in the mod, or isn't easily accessable is EA level stupid.

**Comment by pWn3d1337** [comment]
Turrets can be powered and no power config option is in the config file.
