### ISSUE TITLE
Attack helicopter is not present or is there but not loaded correctly.

### ISSUE THREAD

**Issue by MrKrabs123yes** [pWn3d1337/Techguns2#163]
There is a glitch where i cant move ANYWHERE because the attack helicopter was loaded in.

here is the error.

// Don't do that.

Time: 10/8/19 10:02 PM
Description: Rendering entity in world

java.lang.ArrayIndexOutOfBoundsException: 5
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.processQuad(VertexLighterFlat.java:237)
	at net.minecraftforge.client.model.pipeline.QuadGatheringTransformer.put(QuadGatheringTransformer.java:66)
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad.pipe(UnpackedBakedQuad.java:78)
	at techguns.client.render.entities.npcs.RenderAttackHelicopter.renderBakedModel(RenderAttackHelicopter.java:153)
	at techguns.client.render.entities.npcs.RenderAttackHelicopter.doRender(RenderAttackHelicopter.java:103)
	at techguns.client.render.entities.npcs.RenderAttackHelicopter.func_76986_a(RenderAttackHelicopter.java:34)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:839)
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:375)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4093)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1592)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.processQuad(VertexLighterFlat.java:237)
	at net.minecraftforge.client.model.pipeline.QuadGatheringTransformer.put(QuadGatheringTransformer.java:66)
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad.pipe(UnpackedBakedQuad.java:78)
	at techguns.client.render.entities.npcs.RenderAttackHelicopter.renderBakedModel(RenderAttackHelicopter.java:153)
	at techguns.client.render.entities.npcs.RenderAttackHelicopter.doRender(RenderAttackHelicopter.java:103)
	at techguns.client.render.entities.npcs.RenderAttackHelicopter.func_76986_a(RenderAttackHelicopter.java:34)

-- Entity being rendered --
Details:
	Entity Type: techguns:attackhelicopter (techguns.entities.npcs.AttackHelicopter)
	Entity ID: 329
	Entity Name: Attack Helicopter
	Entity's Exact location: 7.80, 103.24, 3.08
	Entity's Block location: World: (7,103,3), Chunk: (at 7,6,3 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: techguns.client.render.entities.npcs.RenderAttackHelicopter@119402b8
	Location: 9.89,33.24,-79.71 - World: (9,33,-80), Chunk: (at 9,2,0 in 0,-5; contains blocks 0,0,-80 to 15,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: 324.84375
	Delta: 0.38000107
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:839)
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:375)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4093)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1592)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['CS_LieM'/297, l='MpServer', x=-2.11, y=70.00, z=82.95]]
	Chunk stats: MultiplayerChunkCache: 358, 358
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (48,64,256), Chunk: (at 0,4,0 in 3,16; contains blocks 48,0,256 to 63,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 73063 game time, 35942 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 90 total; [ZombieFarmer['Zombie Farmer'/128, l='MpServer', x=31.50, y=33.00, z=158.50], EntityRabbit['Rabbit'/129, l='MpServer', x=26.57, y=69.00, z=154.89], ZombieMiner['Zombie Miner'/130, l='MpServer', x=31.50, y=33.00, z=160.50], EntityRabbit['Rabbit'/132, l='MpServer', x=32.01, y=69.00, z=97.50], EntityRabbit['Rabbit'/133, l='MpServer', x=42.50, y=70.00, z=139.50], EntityRabbit['Rabbit'/134, l='MpServer', x=41.40, y=69.00, z=139.40], EntityRabbit['Rabbit'/135, l='MpServer', x=42.27, y=70.31, z=142.65], EntityRabbit['Rabbit'/136, l='MpServer', x=38.47, y=69.00, z=158.43], EntityRabbit['Rabbit'/139, l='MpServer', x=55.42, y=70.00, z=117.50], EntityRabbit['Rabbit'/140, l='MpServer', x=61.60, y=71.46, z=117.13], EntityBat['Bat'/145, l='MpServer', x=73.56, y=14.04, z=95.66], EntityRabbit['Rabbit'/146, l='MpServer', x=64.50, y=71.00, z=117.50], EntityRabbit['Rabbit'/147, l='MpServer', x=76.50, y=76.00, z=126.03], SkeletonSoldier['Skeleton Soldier'/298, l='MpServer', x=-17.59, y=53.00, z=4.51], EntityBat['Bat'/303, l='MpServer', x=-81.49, y=42.12, z=50.89], EntityBat['Bat'/304, l='MpServer', x=-50.19, y=45.10, z=18.53], EntityBat['Bat'/305, l='MpServer', x=-50.50, y=43.01, z=17.22], ArmySoldier['Army Soldier'/314, l='MpServer', x=20.50, y=70.00, z=24.50], ArmySoldier['Army Soldier'/315, l='MpServer', x=19.50, y=70.00, z=28.50], Bandit['Bandit'/316, l='MpServer', x=42.50, y=31.00, z=7.50], ZombieFarmer['Zombie Farmer'/61, l='MpServer', x=-67.50, y=31.00, z=85.50], ArmySoldier['Army Soldier'/317, l='MpServer', x=14.50, y=70.00, z=17.50], ZombieFarmer['Zombie Farmer'/62, l='MpServer', x=-67.50, y=31.00, z=86.50], ArmySoldier['Army Soldier'/318, l='MpServer', x=6.50, y=69.00, z=21.50], ZombieMiner['Zombie Miner'/63, l='MpServer', x=-68.50, y=13.00, z=124.50], ArmySoldier['Army Soldier'/319, l='MpServer', x=7.50, y=69.00, z=24.50], ZombieFarmer['Zombie Farmer'/64, l='MpServer', x=-67.78, y=13.00, z=125.50], ArmySoldier['Army Soldier'/320, l='MpServer', x=5.50, y=69.00, z=28.50], ZombieFarmer['Zombie Farmer'/65, l='MpServer', x=-68.50, y=13.00, z=127.50], ArmySoldier['Army Soldier'/321, l='MpServer', x=13.50, y=70.00, z=25.50], EntitySkeleton['Skeleton'/66, l='MpServer', x=-55.50, y=39.00, z=67.50], EntitySkeleton['Skeleton'/67, l='MpServer', x=-56.50, y=39.00, z=67.50], ArmySoldier['Army Soldier'/323, l='MpServer', x=20.50, y=69.00, z=7.50], EntitySkeleton['Skeleton'/68, l='MpServer', x=-59.50, y=39.00, z=66.50], ArmySoldier['Army Soldier'/324, l='MpServer', x=19.50, y=70.00, z=11.50], EntitySkeleton['Skeleton'/69, l='MpServer', x=-58.50, y=39.00, z=66.50], EntityBat['Bat'/325, l='MpServer', x=-16.85, y=58.07, z=0.80], EntitySquid['Squid'/70, l='MpServer', x=-59.40, y=55.31, z=127.81], ArmySoldier['Army Soldier'/326, l='MpServer', x=7.50, y=70.00, z=7.50], EntitySquid['Squid'/71, l='MpServer', x=-59.84, y=51.10, z=119.97], ArmySoldier['Army Soldier'/327, l='MpServer', x=5.50, y=70.00, z=11.50], EntitySquid['Squid'/72, l='MpServer', x=-59.40, y=51.16, z=120.00], ArmySoldier['Army Soldier'/328, l='MpServer', x=13.50, y=69.00, z=8.50], EntityRabbit['Rabbit'/73, l='MpServer', x=-32.50, y=68.00, z=75.50], AttackHelicopter['Attack Helicopter'/329, l='MpServer', x=7.80, y=103.24, z=3.08], ZombieMiner['Zombie Miner'/74, l='MpServer', x=-41.50, y=40.00, z=94.50], ZombieFarmer['Zombie Farmer'/75, l='MpServer', x=-44.50, y=14.00, z=143.50], Bandit['Bandit'/331, l='MpServer', x=37.50, y=56.00, z=34.50], ZombieFarmer['Zombie Farmer'/76, l='MpServer', x=-42.50, y=14.00, z=142.50], EntityCreeper['Creeper'/332, l='MpServer', x=26.54, y=55.00, z=46.46], EntityZombieVillager['Zombie Villager'/77, l='MpServer', x=-44.50, y=14.00, z=140.50], ZombieMiner['Zombie Miner'/78, l='MpServer', x=-47.50, y=14.00, z=149.50], ZombieFarmer['Zombie Farmer'/79, l='MpServer', x=-45.50, y=14.00, z=145.50], EntityZombie['Zombie'/80, l='MpServer', x=-42.50, y=14.00, z=145.50], EntityZombie['Zombie'/81, l='MpServer', x=-45.33, y=14.00, z=148.17], EntityZombie['Zombie'/82, l='MpServer', x=-40.50, y=14.00, z=145.50], EntitySkeleton['Skeleton'/83, l='MpServer', x=-43.50, y=14.00, z=146.50], EntityRabbit['Rabbit'/340, l='MpServer', x=73.68, y=73.00, z=57.94], EntityRabbit['Rabbit'/342, l='MpServer', x=73.55, y=73.00, z=56.98], EntityRabbit['Rabbit'/90, l='MpServer', x=-28.50, y=68.00, z=78.50], EntityRabbit['Rabbit'/91, l='MpServer', x=-28.27, y=68.00, z=79.11], EntityZombie['Zombie'/92, l='MpServer', x=-18.50, y=30.00, z=137.50], EntityEnderman['Enderman'/93, l='MpServer', x=-20.50, y=24.00, z=152.50], EntityCreeper['Creeper'/94, l='MpServer', x=-17.50, y=30.00, z=158.50], ZombieFarmer['Zombie Farmer'/95, l='MpServer', x=-19.50, y=30.00, z=154.50], EntitySkeleton['Skeleton'/96, l='MpServer', x=-19.50, y=25.00, z=157.50], EntityPlayerSP['CS_LieM'/297, l='MpServer', x=-2.11, y=70.00, z=82.95], SkeletonSoldier['Skeleton Soldier'/97, l='MpServer', x=-20.50, y=29.00, z=150.86], ZombieFarmer['Zombie Farmer'/98, l='MpServer', x=-19.50, y=30.00, z=144.50], EntityBat['Bat'/99, l='MpServer', x=-21.34, y=29.21, z=148.25], ZombieFarmer['Zombie Farmer'/102, l='MpServer', x=-3.50, y=43.00, z=68.50], ZombieMiner['Zombie Miner'/103, l='MpServer', x=-3.50, y=43.00, z=70.50], ZombieFarmer['Zombie Farmer'/104, l='MpServer', x=-6.50, y=45.00, z=69.50], EntitySpider['Spider'/105, l='MpServer', x=-9.50, y=30.00, z=125.50], ZombieFarmer['Zombie Farmer'/106, l='MpServer', x=-8.50, y=30.00, z=126.50], ZombieFarmer['Zombie Farmer'/107, l='MpServer', x=-10.50, y=23.00, z=142.15], SkeletonSoldier['Skeleton Soldier'/109, l='MpServer', x=1.50, y=14.00, z=134.50], ZombieFarmer['Zombie Farmer'/110, l='MpServer', x=4.50, y=18.00, z=146.50], ZombieFarmer['Zombie Farmer'/111, l='MpServer', x=4.50, y=18.00, z=147.50], Bandit['Bandit'/112, l='MpServer', x=2.50, y=18.00, z=144.50], SkeletonSoldier['Skeleton Soldier'/113, l='MpServer', x=2.50, y=18.00, z=145.50], ZombieMiner['Zombie Miner'/119, l='MpServer', x=23.50, y=15.00, z=79.50], EntityBat['Bat'/120, l='MpServer', x=23.46, y=15.35, z=78.80], EntityBat['Bat'/121, l='MpServer', x=16.83, y=17.22, z=76.43], SkeletonSoldier['Skeleton Soldier'/122, l='MpServer', x=20.50, y=26.00, z=80.50], EntityRabbit['Rabbit'/123, l='MpServer', x=21.19, y=70.00, z=93.46], EntityRabbit['Rabbit'/124, l='MpServer', x=26.45, y=70.00, z=84.33], EntityBat['Bat'/125, l='MpServer', x=19.32, y=28.67, z=105.84], EntityBat['Bat'/126, l='MpServer', x=29.60, y=30.01, z=105.21], ZombieFarmer['Zombie Farmer'/127, l='MpServer', x=25.50, y=40.00, z=152.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 870755464 bytes (830 MB) / 1610612736 bytes (1536 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2846 Optifine OptiFine_1.12.2_HD_U_E3 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version           | Source                             | Signature                                |
	|:------ |:----------------- |:----------------- |:---------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2            | minecraft.jar                      | None                                     |
	| LCHIJA | mcp               | 9.42              | minecraft.jar                      | None                                     |
	| LCHIJA | FML               | 8.0.99.99         | forge-1.12.2-14.23.5.2846.jar      | None                                     |
	| LCHIJA | forge             | 14.23.5.2846      | forge-1.12.2-14.23.5.2846.jar      | None                                     |
	| LCHIJA | creativecoredummy | 1.0.0             | minecraft.jar                      | None                                     |
	| LCHIJA | littletilescore   | 1.0.0             | minecraft.jar                      | None                                     |
	| LCHIJA | techguns_core     | 1.12.2-1.0        | minecraft.jar                      | None                                     |
	| LCHIJA | artemislib        | 1.0.6             | ArtemisLib-1.12.2-v1.0.6.jar       | None                                     |
	| LCHIJA | blockcraftery     | 1.12.2-1.1.0      | Blockcraftery-Mod-1.12.2.jar       | None                                     |
	| LCHIJA | ctm               | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar          | None                                     |
	| LCHIJA | chisel            | MC1.12.2-0.2.1.35 | Chisel-MC1.12.2-0.2.1.35.jar       | None                                     |
	| LCHIJA | codechickenlib    | 3.2.2.353         | CodeChickenLib-1.12.2.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | creativecore      | 1.9.9             | CreativeCore-1.12.2.jar            | None                                     |
	| LCHIJA | cfm               | 6.3.1             | furniture-6.3.1-1.12.2.jar         | None                                     |
	| LCHIJA | jei               | 4.15.0.289        | jei_1.12.2-4.15.0.289.jar          | None                                     |
	| LCHIJA | littletiles       | 1.5.0             | LittleTiles-Mod-1.12.2.jar         | None                                     |
	| LCHIJA | resize            | 2.1.2             | resizingpotion-2.1.2.jar           | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
	| LCHIJA | techguns          | 2.0.2.0           | techguns-1.12.2-2.0.2.0_pre3.1.jar | None                                     |
	| LCHIJA | mysticallib       | 1.12.2-1.3.5      | MysticalLib-1.12.2.jar             | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore-1.12.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
  techguns.core.TechgunsASMTransformer
LittlePatchingLoader (LittleTiles-Mod-1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-1.68.23' Renderer: 'AMD Radeon Pro 570 OpenGL Engine'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2846
	LWJGL: 2.9.2
	OpenGL: AMD Radeon Pro 570 OpenGL Engine GL version 2.1 ATI-1.68.23, ATI Technologies Inc.
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.22 Lite.zip
	OpenGlVersion: 2.1 ATI-1.68.23
	OpenGlRenderer: AMD Radeon Pro 570 OpenGL Engine
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by ben-mkiv** [comment]
Disabling Optifine would work around the issue.
