### ISSUE TITLE
The square box when using shaders

### ISSUE THREAD

**Issue by DeLiWrAp** [pWn3d1337/Techguns2#165]
As in https://github.com/pWn3d1337/Techguns2/issues/121 and https://github.com/pWn3d1337/Techguns2/issues/113; I'm having the square appear when I fire a gun by water or glass using Sildur's Enhanced Default Shaders (https://sildurs-shaders.github.io/).

Running the latest version of Optifine and the latest version of Forge with this mod works fine, I've managed to single out the issue and believe it is similar to this:
https://www.reddit.com/r/Minecraft/comments/6i0n2q/shaders_stained_glasswater_bug/

Would there be any way to correct for this? 

Just to reiterate, Optifine without shaders works perfectly - there is no square unless I start using shaders.

**Comment by pWn3d1337** [comment]
I can't do something against this, the shader mod would have to
