### ISSUE TITLE
Console spam and some Exception

### ISSUE THREAD

**Issue by Vitali8** [pWn3d1337/Techguns2#17]
Repeat of Techguns [#135](https://github.com/pWn3d1337/Techguns/issues/135), to match mod's version, with which problems arise.
I have some spam in the server console. Server console are clogging up with errors, when you somehow interact with a mob (zombie, helicopter) from the mod. I tried to put a spawn on 0 in configs, but this doesn't solve the problem, because in some or other quantities the mobs continue to spawn.

Example error from console: [Error](https://gist.github.com/Vitali8/61f756e1b51ec99612bc7f54aec726fc)

Also, sometimes there is such an Exception: [Exception occurred during a PhaseState](https://gist.github.com/Vitali8/ecb4e6c2d1715888360c66dad4210508)

**Comment by mallrat208** [comment]
The problem stems from here
https://github.com/pWn3d1337/Techguns2/blob/ea71f93e0092d1251f7f9b82ce057278a3a6f0f1/src/main/java/techguns/items/armors/GenericArmor.java#L469

Generally speaking even though that method requires an instance of EntityPlayer as a parameter, it can be safely passed a null as the only thing the instance of EntityPlayer does there is for stat tracking for item damaged.

Alternatively you could do something like this to add it in as required...

```
if (stack.attemptDamageItem(damage, entity.getRNG(), (entity instanceof EntityPlayerMP ?
 (EntityPlayerMP) entity : null)))
```
