### ISSUE TITLE
Feature Request: Server Override for Block Damage

### ISSUE THREAD

**Issue by mallrat208** [pWn3d1337/Techguns2#20]
I really like that Techguns let's you specify whether you want to have block damage occur or not, it's a great feature, but it would be really nice if there was a config option to forcibly prevent damage for use on a serve where you cannot count on or expect others to remember to check their settings.

**Comment by pWn3d1337** [comment]
It is registered as permission to forge API:

https://github.com/pWn3d1337/Techguns2/blob/master/src/main/java/techguns/TGPermissions.java

**Comment by mallrat208** [comment]
That's useful but doesn't help in this instance as it only works if you're using something to manage permissions like say FTBUtil for Claimed Chunks.

If you have techguns by itself on a server, there's no way for the server to say 'don't damage blocks'

**Comment by pWn3d1337** [comment]
There is an option to disallow unsafe mode for non-ops.
