### ISSUE TITLE
Invisible Zombies

### ISSUE THREAD

**Issue by kerbalkommander** [pWn3d1337/Techguns2#203]
After a few hours into any singleplayer session, I find I'm attacked by an invisible zombie miner or farmer, that can only be interacted with by shooting it with techguns weaponry. Any local fix for this?

**Comment by Master-Henry2006** [comment]
I never had this issue, but it could be an incompatibility with another mod. I don't think it is a bug of the mod techguns.

**Comment by pWn3d1337** [comment]
Very likely a compatibility problem, never heard of this "bug".
