### ISSUE TITLE
Cannot Reload weapons with Incendiary Ammo

### ISSUE THREAD

**Issue by TeetoKaziim** [pWn3d1337/Techguns2#204]
Forge Version: 14.5.23.2847
Techguns Version: 1.12.2-2.0.2.0_pre31
Also Installed:
Just Enough Items: 1.12.2-4.15.0.293

Upon emptying their ammo reserves, and having available incendiary ammo in the inventory, none of the weapons here seem to be able to reload with said Incendiary ammo.

To the best of my ability to determine, this applies to all weapons whom'ses ammo has an incendiary ammunition variant.

![image](https://user-images.githubusercontent.com/25490944/80860729-57a4ef80-8c2f-11ea-8613-081be575e308.png)

This also seems to occur regardless of if the ammo is in the player's main minecraft inventory, or, in the techguns ammo inventory.

The moment normal non-incendiary ammo is introduced to the player's inventory, the guns are able to be reloaded with that.

**Comment by Master-Henry2006** [comment]
Before you are able to reload, you have to craft the weapon and the ammo together. Jei shows the recipe.

**Comment by TeetoKaziim** [comment]
Oh dear, thankyou, sorry.
