### ISSUE TITLE
Damage applying issues

### ISSUE THREAD

**Issue by roboderpy** [pWn3d1337/Techguns2#21]
So, Techguns seems to impropely apply damage to players. Because of this, next issues appears:
* Bullets ignore Draconic's Evolution armour's shield
* Bullets are unaffected by Projectile Protection enchantment
* Last Stand from OpenBlocks doesn't prevent player death if he takes damage from a gun
and some other issues which i can't remember...

**Comment by pWn3d1337** [comment]
The last stand enchantment should be fixed by calling the appropriate event in the techguns damage system. The event was added to forge after the code was written.
