### ISSUE TITLE
Techguns mobs are badly inherited

### ISSUE THREAD

**Issue by roboderpy** [pWn3d1337/Techguns2#22]
E. G. Zombies and skeletons and pigmans are not taking extra damage from Smite, Pigman Soldier can easily anger an army of vanilla pigmans towards the TG pigman and all players, like if techguns pigman were a player. Also some other misc issues.

**Comment by roboderpy** [comment]
Also TE zombies can be poisoned and healed using instant healing

**Comment by Sixdd6** [comment]
There are also issues with TechGuns mobs when using MobStages. TG mobs do not obey any rules set to not spawn by MobStages. I'm just guessing but I'd say it's related so I posted it here.
