### ISSUE TITLE
Cannot scope when left and right mouse buttons are swapped

### ISSUE THREAD

**Issue by Kiako1** [pWn3d1337/Techguns2#228]
On Techguns 2.0.2.0, if the use/build and attack/destroy buttons are swapped, using the right-click (now destroy) causes the gun to do a sort of drop motion instead of scoping (tested with Bolt Action Rifle.)

Unsure if this is fixable or if it‘s just a Minecraft issue, since I have heard that overriding the attack action is difficult.

**Comment by pWn3d1337** [comment]
Attack override is done my cancelling Mouse Input events. Rebinding is not supported.
