### ISSUE TITLE
GuidedMissleLauncher can't be changed in scripts

### ISSUE THREAD

**Issue by Minecr4ck** [pWn3d1337/Techguns2#237]
Hello, 
Attempting to change the guidedmisslelauncher gives back the following error, and it says its "NOT A GUN"

[INITIALIZATION][CLIENT][INFO] Set [DAMAGE_MIN] for Weapon: [grimreaper] to: 500.0
[INITIALIZATION][CLIENT][INFO] Set [DAMAGE] for Weapon: [grimreaper] to: 500.0
**[INITIALIZATION][CLIENT][INFO] Failed setting [DAMAGE_MIN] for Weapon: [guidedmisslelauncher]: ITEM IS NOT A GUN
[INITIALIZATION][CLIENT][INFO] Failed setting [DAMAGE] for Weapon: [guidedmisslelauncher]: ITEM IS NOT A GUN**
[INITIALIZATION][CLIENT][INFO] Set [DAMAGE_MIN] for Weapon: [grenadelauncher] to: 180.0
[INITIALIZATION][CLIENT][INFO] Set [DAMAGE] for Weapon: [grenadelauncher] to: 180.0

Here is part of my script

GunStats.setWeaponStat("grimreaper","DAMAGE_MIN",500);
GunStats.setWeaponStat("grimreaper","DAMAGE",500);
GunStats.setWeaponStat("guidedmisslelauncher","DAMAGE_MIN",800);
GunStats.setWeaponStat("guidedmisslelauncher","DAMAGE",800);

GunStats.setWeaponStat("grenadelauncher","DAMAGE_MIN",180);
GunStats.setWeaponStat("grenadelauncher","DAMAGE",180);

Did I do this incorrectly? Or is this a bug?

Thanks in advance!

**Comment by pWn3d1337** [comment]
you misspelled guidedmissilelauncher
