### ISSUE TITLE
Is it possible to decrease the damage of all guns against mobs?

### ISSUE THREAD

**Issue by Krid3l** [pWn3d1337/Techguns2#24]
Hello everyone,

I'm using TechGuns along with Tinker's Construct and other metallurgy/melee-weapon related mods. I absolutely love TechGuns, however the gun's damage outputs are a little OP compared to melee weapons, so it discourages me and my friends on my server to use anything else. I tried changing the S:DamageFactorNPC value in the config, but it dosen't seem to change anything. Anyone has an idea?

Thanks in advance.

**Comment by pWn3d1337** [comment]
DamageFactorNPC reduces the damage npcs do with the guns. You can nerf the guns through crafttweaker.

https://github.com/pWn3d1337/Techguns2/blob/master/src/main/java/techguns/plugins/crafttweaker/GunStatTweaker.java

https://github.com/pWn3d1337/Techguns2/blob/master/src/main/java/techguns/plugins/crafttweaker/EnumGunStat.java

**Comment by Krid3l** [comment]
Excellent! Thank you very much, pWn3d.

Since I'm a bit of a newbie in Java, what am I supposed to do with these two files to make them work in conjunction with TechGuns?

Best regards.

**Comment by pWn3d1337** [comment]
You write a crafttweaker script, you need the crafttweaker mod obviously. Crafttweaker is a mod that allows you to manipulate mincraft recipes and also modded machine recipes and other stuff if the mod allows it.  The files I linked are the available methods for techguns gun stat tweaking, armor stats and machine recipes can also be manipulated with crafttweaker

**Comment by Krid3l** [comment]
Thanks a lot for these instructions. I'll try that in a couple days and post the results here. Cheers.

**Comment by Krid3l** [comment]
Hello again! So, I wrote a little CraftTweaker script with the methods you wrote in the .java files you provided me in your previous messages. However it dosen't seem to work - I think I did something wrong. Am I supposed to drop the two .java files in the "script" folder or do I have to put them somewhere else?

Sorry for bothering you with that, I'm completely new to this. ^u^'

Best regards.
