### ISSUE TITLE
mobs have invincibility frames after getting shot

### ISSUE THREAD

**Issue by Marrynd** [pWn3d1337/Techguns2#262]
I'm trying out rebirth of the night mod-pack, mob only take damage from the first shot afterward the gain some sort of invincibility frames for a few second, for shotgun they only take damage from one pallet

**Comment by pWn3d1337** [comment]
Seems like a Modpack problem. There must be another mod interfering with event handlers.

**Comment by Marrynd** [comment]
is there any past incident of this kind of compatibility issue that might be causing this

**Comment by Marrynd** [comment]
Alright, I found the dang thing. the mod that been causing this is Better hurt timer hope this help someone in the future
