### ISSUE TITLE
Unfillable Fuel Tank

### ISSUE THREAD

**Issue by Sibith** [pWn3d1337/Techguns2#27]
Have no way of refilling the fuel tank. Maybe I'm just dumb, but when I put an full one in the Chemical Laboratory it just empties it and trying to fill an empty one doesn't work. I'm using this with the Mekanism mod if that means anything. Just wondering if this is backwards. Haven't seen anyone else who had this problem.

**Comment by gustavoms00** [comment]
I also can't find a way to fill fuel tanks or compressed air tanks either, would be really glad if someone explained how to.

**Comment by Froggy800** [comment]
@Sibith Fuel tanks need 250 mb of biofuel to be filled - I know for sure Industrial foregoing's works without issues.
@gustavoms00 You need to pump water in the chemical laboratory and give it RF, then put the empty compressed air tank and a piece of coal.

**Comment by Sibith** [comment]
Just tried that that and it didn't work but it works for the bio tank so I think u may be confused

**Comment by Froggy800** [comment]
The bio tank needs water to fill up, not biofuel. If you don't have biofuel there's no way to fill the tanks. Does JEI show anything in the recipe for the filled tank in the chemical lab tab?
![2018-03-13_14 37 55](https://user-images.githubusercontent.com/25703114/37345141-2a8ca042-26c4-11e8-8093-763dc12868e4.png)
![2018-03-13_14 40 00](https://user-images.githubusercontent.com/25703114/37345144-2ab81e0c-26c4-11e8-8b70-6c77beb1604e.png)

**Comment by Sibith** [comment]
Oh there's my problem I need industrial foregoings to get liquid biofuel. I'll just trade it out with the mekanism mod. I have JEI and a recipe would never pop up but I guess this is why. I still think @pWn3d1337 should have mentioned that u need a mod that adds liquid biofuel or just make fuel tanks fillable without the requirement of another mod. Thanks so much!

**Comment by Froggy800** [comment]
No problem. I just noticed that you can also use Refined Fuel from Thermal Expansion in place of IF's biofuel.
You could easily use a CraftTweaker script to fill a tank, since they are simply two different items and not fluid containers, no need to avoid the mod just for that issue - something like this would work (shapeless recipe using bio mass):
recipes.addShapeless(<techguns:itemshared:27>, [<techguns:itemshared:28>,<techguns:itemshared:61>]);

**Comment by Sibith** [comment]
Oh thanks! That's seriously helps so much. I've heard of crafttweaker before and thought about trying it but I didn't know have. This helps a lot. I'll have to mess around with the script and get it work good. Thanks again!

**Comment by pWn3d1337** [comment]
Fuel tanks use fuel from other mods if it's present. If no fuel is present the recipe needs lava.

**Comment by Froggy800** [comment]
There's something wrong with the recipe script, apparently - You can place filled fuel tanks in the input slot and the chemical laboratory will proceed to give you back an empty fuel tank and 500 mb of lava
![2018-03-14_14 14 06](https://user-images.githubusercontent.com/25703114/37404530-0ba8edea-278a-11e8-8141-b002985e639b.png)

By the way, I just noticed that I posted [this issue](https://github.com/pWn3d1337/Techguns/issues/149) on the wrong issue tracker. Should I remake it in this one?

**Comment by Sibith** [comment]
@pWn3d1337 Oh now I remember, I was messing with the config and did something with the lava fuel recipes thing not knowing what it did 😅 that helps alot. Thank you!

**Comment by Sibith** [comment]
@pwn3d1337 actually tried fixing the config, but something is still very wrong. I want it to work with lava by default but messing with the config does nothing. Its the only part of the config that doesn't seem to work
