### ISSUE TITLE
Update the mod to 1.16

### ISSUE THREAD

**Issue by kirillgla** [pWn3d1337/Techguns2#270]
The title is pretty self-explanatory. This is an amazing mod which a lot of people would be happy to see ported to newer version of minecraft

**Comment by PyroSimba** [comment]
Why would you post this under issues???

**Comment by kirillgla** [comment]
Because I'm not sure where else I'd post this. What is the more suitable place for this?

**Comment by PyroSimba** [comment]
No where. The next version of the mod will come when it comes.

**Comment by kirillgla** [comment]
You are being very toxic for no reason, sir
