### ISSUE TITLE
How to set up Techguns code in Eclipse

### ISSUE THREAD

**Issue by cadergator10** [pWn3d1337/Techguns2#272]
Hello. So I have been wanting to maybe try and edit some of the code for a modpack I have. It's a SCP modpack and I wanted to duplicate the Nuclear Ray, but edit some parameters like super short range, but high damage and must be charged...

None of that is important up there, but what I can't figure out is how to import it to Eclipse error free. I tried using Forge Mod Maker to make a workspace, then import the files afterward, but there are still errors.

**Comment by cadergator10** [comment]
Just read License and wanted to let you know, that I am not going to release it on curseforge or anything. It is going to only be for my modpack, which leads into a second question: am I allowed to edit it only for my modpack?

**Comment by PyroSimba** [comment]
I don't think you can modify the code if you plan on distributing your modpack. Doing so goes against the license.

**Comment by cadergator10** [comment]
> I don't think you can modify the code if you plan on distributing your modpack. Doing so goes against the license.

Ok then, nvr mind
