### ISSUE TITLE
Tile entity duping with Mining Drill

### ISSUE THREAD

**Issue by Froggy800** [pWn3d1337/Techguns2#31]
Breaking some tile entities with the Mining Drill's aoe can have undesired results:
- Storage drawers: the cursor targeted drawer gets mined and dropped correctly, but you get up to 7 extra drops from the other drawers - the duped drawers completely lose their nbt tag, but keep their metadata.
- Thermal expansion machine/dynamo: all machines drop correctly, but you get up to 8 extra drops - the duped machines have an empty nbt tag and lose their metadata, turning into steam dynamos / redstone furnaces

**Comment by pWn3d1337** [comment]
As a fix the mining drill aoe will no longer work on tile entities as it can cause severe problems with other mods.
