### ISSUE TITLE
Missing recipes

### ISSUE THREAD

**Issue by Froggy800** [pWn3d1337/Techguns2#32]
The Blaster Shotgun and the Alien Blaster cannot be crafted, since they don't have a recipe.

**Comment by VioletWyvern** [comment]
Because these are only collected by looting...

**Comment by Froggy800** [comment]
Except you cannot? The closest thing you can get is the Blaster Rifle from the Stormtroopers and the Outcasts, and they don't even seem to spawn normally.
Unless I'm missing something else, there's no way to obtain those weapons.

**Comment by VioletWyvern** [comment]
Finded the missing recipe in by using NEI:
<a href="https://imgur.com/N49h19O"><img src="https://i.imgur.com/N49h19O.png" title="source: imgur.com" /></a>
