### ISSUE TITLE
Can't Display Weapons

### ISSUE THREAD

**Issue by DonMegel** [pWn3d1337/Techguns2#36]
When I put a gun in an item frame, or on a Bibliocraft shelf, it points in a weird direction. Is there a fix for this or some other way to display these great guns on the wall?

**Comment by BrisingrAerowing** [comment]
I personally use pedestals for displaying things. I think the issue you have is because the items are 3D models, and the item frame / shelf doesn't like that.

**Comment by pWn3d1337** [comment]
Vanilla item frames have the items correctly positioned, everything else is out of my control.
