### ISSUE TITLE
Ignoring check instance and casting causes ClassCastException

### ISSUE THREAD

**Issue by gabizou** [pWn3d1337/Techguns2#38]
In relation to https://github.com/SpongePowered/SpongeForge/issues/2139, [GenericArmor](https://github.com/pWn3d1337/Techguns2/blob/150cef027b2e61173ac2fe5cbd9f3ec162431316/src/main/java/techguns/items/armors/GenericArmor.java#L455-L469) is casting to `EntityPlayerMP`, even though there's an instance check. This is causing spam exceptions when players are taking damage with this sort of armor.

I'm not fully understanding the point of the instance check, but even an IDE will flag this as a warning as shown below:
<img width="1062" alt="screen shot 2018-05-11 at 1 25 27 pm" src="https://user-images.githubusercontent.com/1203877/39945317-e483d1ea-551e-11e8-8018-78b4f359255f.png">

**Comment by pyscho974** [comment]
seems like the place to make a reference for this tho this post starts with older sponge version then what is in the reference im  adding to this post

https://github.com/SpongePowered/SpongeForge/issues/2204
