### ISSUE TITLE
No loot in structures

### ISSUE THREAD

**Issue by KatoMarika** [pWn3d1337/Techguns2#4]
Chests in structures (Not military base) dont have any loot.
https://i.imgur.com/KaCvCse.png
https://i.imgur.com/xHFovTk.png

**Comment by pWn3d1337** [comment]
Yes, those 2 have no loottables set yet.

**Comment by pWn3d1337** [comment]
will be added next release

**Comment by pWn3d1337** [comment]
Will be added next release
