### ISSUE TITLE
Exo Suit not charging with the charging station or energetic infuser

### ISSUE THREAD

**Issue by F34RxPredator** [pWn3d1337/Techguns2#41]
The exo suit from tech guns supports RF but doesn't seem to charge in the tech guns charging station or thermal expansions energetic infuser, is this for a reason or is this a bug that needs to be fixed. As the hardcore pack im working on the exo suit would be very useful in.

**Comment by pWn3d1337** [comment]
Armors use ammo from inventory and are not charged.
