### ISSUE TITLE
TG 2.0.1.2_pre1 crash

### ISSUE THREAD

**Issue by BrisingrAerowing** [pWn3d1337/Techguns2#46]
[Crash Log](https://gist.github.com/BrisingrAerowing/c6eb9ac8f39d87ac2b27329c27b0f27a)

Happens on loading the game with Exotic Birds. It seems that the RADIATION_RESISTANCE attribute instance is null at entity construction.

**Comment by BrisingrAerowing** [comment]
I just did a quick decompile of EB and they are registering entities and stuff in preinit, so this is on their end to fix.

**Comment by pWn3d1337** [comment]
No, this is an issue, the RADIATION_RESISTANCE is currently only available with debug=true and should not be called.

**Comment by pWn3d1337** [comment]
Should be fixed with pre-release2

**Comment by HydrogenC** [comment]
By the way, are you still working on Techguns?
