### ISSUE TITLE
EnderIO Fuel Support for Fuel Tanks

### ISSUE THREAD

**Issue by mallrat208** [pWn3d1337/Techguns2#47]
When using Techguns with EnderIO, none of the EnderIO Fuels count as a fuel.

EnderIO add's in three combustible fuels, Hootch ("hootch"), Fire Water ("fire_water"), and Rocket Fuel ("rocket_fuel"). They are all grain alcohol based and crafted using the EIO Vat.

Hootch is equivalent to most mods Bio Fuel with Fire Water and Rocket Fuel each being a further refined version of that with Rocket Fuel being the highest generating amount, roughly on par with Fuel from other mods.

**Comment by pWn3d1337** [comment]
The following fluids will be accepted as fuels in next version:
{"fuel", "refined_fuel", "biofuel", "biodiesel", "diesel", "gasoline", "refined_biofuel", "fire_water", "rocket_fuel"}
