### ISSUE TITLE
What's the "cross" inventory slot for?

### ISSUE THREAD

**Issue by ZXQWAS** [pWn3d1337/Techguns2#52]
I can't seem to find what the cross inventory slot is for (near food), how is it special. There is a page on TG1 wiki which doesn't have it https://github.com/pWn3d1337/Techguns/wiki/Techguns-Inventory-Tab, there's no such page on the TG2 wiki. I can't find any explanation anywhere too.

**Comment by pWn3d1337** [comment]
This slot is not yet in use. The plan is for auto healing items, like a stim pack for example.
