### ISSUE TITLE
Mob drops have empty NBT Tags (Not Fixed)

### ISSUE THREAD

**Issue by Trellinane** [pWn3d1337/Techguns2#53]
Mob drops have empty NBT tags.  I saw this reported before and labeled with bug and fixed labels in Jan.  This is not fixed.  It is causing bigger issues than things just not stacking.  Most of the Mekanism machines will not accept the items with the NBT tags.  Crusher will not accept gunpowder with the empty NBT tag Metallurgic Infuser will not accept iron ingots with the NBT tag.  Finally, it crashes the game when my Refined Storage system tries to autocraft using items with the NBT tag because they will not go into the Mekanism machines.  

Love this mod but I may have to remove if this continues.  Please fix.  Thank you.

Minecraft 1.12.2
Forge 14.23.4.2739
Techguns-1.12.2-2.0.1.1
Refined Storage 1.6.3
Mekanism-1.12.2-9.4.13.349

**Comment by ZXQWAS** [comment]
Use https://github.com/pWn3d1337/Techguns2/releases/tag/2.0.1.2_pre2

**Comment by Agr10n** [comment]
https://github.com/mallrat208/TG2Helper/releases/tag/1.0.1
