### ISSUE TITLE
Can you teach me how to make it impossible for users other than OPS to use a mode other than security mode? My ability is limited, I can't finish it.

### ISSUE THREAD

**Issue by xingcheng2** [pWn3d1337/Techguns2#59]
Can you teach me how to make it impossible for users other than OPS to use a mode other than security mode?
My ability is limited, I can't finish it.

**Comment by xingcheng2** [comment]
This mod is great, but it can't disable that option in the configuration file, like 1.7.10, which is a drawback

**Comment by pWn3d1337** [comment]
There is a permission that determines if you can use unsafe mode or not:

I explained in in this issue:
https://github.com/pWn3d1337/Techguns2/issues/51

**Comment by xingcheng2** [comment]
Hello, setting permissions does not solve this problem! I tried to delete all the permissions of all people, do not retain any permissions, no permissions! But you can switch security mode by B.

**Comment by pWn3d1337** [comment]
If permissions do not work it's bugged.

**Comment by xingcheng2** [comment]
Haven't you fixed it yet?
![pl_g579o u3snxta 7sud](https://user-images.githubusercontent.com/42384475/45493697-f4d4bb00-b7a1-11e8-8c0b-e6b76e810ff0.png)
I have deleted the permissions, but I can still switch mode.
