### ISSUE TITLE
[Load error] Some item textures not loading.

### ISSUE THREAD

**Issue by Deightine** [pWn3d1337/Techguns2#63]
Doing a bit of my own mod testing and bumped into this stack of errors being thrown during load.

    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/steam_helmet.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/bunkerdoor.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/assaultriflemagazineempty.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/steam_leggings.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/rocket_nuke.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/assaultriflemagazine.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/t3_power_boots.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/steam_boots.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/t3_power_leggings.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/rocket.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/steam_chestplate.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/lmgmagazineempty.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/as50magazine_incendiary.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/door3x3.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/assaultriflemagazine_incendiary.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/lmgmagazine_incendiary.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/t3_power_chestplate.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/dummy.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/as50magazineempty.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/as50magazine.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/lmgmagazine.png, java.io.FileNotFoundException
    [main/ERROR]: Using missing texture, unable to load techguns:textures/items/t3_power_helmet.png, java.io.FileNotFoundException

I checked the assets lists in the jar and it looks like the files for some/all aren't in there in file form. Which would explain the exception. Figured it'd be helpful for you to have the list.

I'm enjoying this port a lot so far! Keep it up! I have a few requests to make once you hit a watershed where you can get to tweaking, but I'll hold'em back for now.

**Comment by pWn3d1337** [comment]
Those are all items that do not have an item but a 3D render in inventory. Minecraft just does not want to accept that. These errors can be ignored.

**Comment by Deightine** [comment]
Ah, gotcha. I'll keep that in mind then.
