### ISSUE TITLE
I can't put rubber and raw plastic in redstone furnance from TE

### ISSUE THREAD

**Issue by An028** [pWn3d1337/Techguns2#65]

**Comment by An028** [comment]
Also could you please make glider's glinding animation look like elytra? Sneaking on air look kinda weird

**Comment by An028** [comment]
Oke thanks!

**Comment by pWn3d1337** [comment]
This problem seems to be related to the order Techguns initializes recipes which caused other bugs like crafttweaker support to not be able to remove recipes. I fixed the init order locally and in the next release this should work.

**Comment by An028** [comment]
Thank you!
