### ISSUE TITLE
When installing the mod FPS is reduced to 20 - 25

### ISSUE THREAD

**Issue by sashazell** [pWn3d1337/Techguns2#68]
My PC: gtx 1060 6g, amd fx 8320 4.4, RAM 16 GB

[latest.log](https://github.com/pWn3d1337/Techguns/files/2451216/latest.log)
[2018-10-05-7.log.gz](https://github.com/pWn3d1337/Techguns/files/2451217/2018-10-05-7.log.gz)
[debug.log](https://github.com/pWn3d1337/Techguns/files/2451218/debug.log)

**Comment by sashazell** [comment]
Before installation
![unknown](https://user-images.githubusercontent.com/21155526/46593531-6ff56c80-cad5-11e8-929a-4e73d60f928b.png)
After installation
![unknown 1](https://user-images.githubusercontent.com/21155526/46593538-7be12e80-cad5-11e8-8e3d-65695248a239.png)

**Comment by pWn3d1337** [comment]
Memory at 92%, try to give it more RAM, most launcher have options for that.

**Comment by sashazell** [comment]
Did not help

![image](https://user-images.githubusercontent.com/21155526/46753273-1012e780-ccc8-11e8-891a-e34bea08b89c.png)

![image](https://user-images.githubusercontent.com/21155526/46753157-be6a5d00-ccc7-11e8-8c4f-bd7725fc3d68.png)
[2018-10-10-2.log.gz](https://github.com/pWn3d1337/Techguns2/files/2465662/2018-10-10-2.log.gz)
[debug-1.log.gz](https://github.com/pWn3d1337/Techguns2/files/2465663/debug-1.log.gz)
[debug.log](https://github.com/pWn3d1337/Techguns2/files/2465664/debug.log)
[latest.log](https://github.com/pWn3d1337/Techguns2/files/2465665/latest.log)

**Comment by pWn3d1337** [comment]
Can't reproduce the problem. I have no fps problems at all (especially when nothing from the mod is rendered) and I have a  GTX 1060 too. Can you show the pie chart?

**Comment by sashazell** [comment]
Maybe the mod is not compatible with AMD?

![image](https://user-images.githubusercontent.com/21155526/46763703-35611f00-cce3-11e8-89ee-455599497bc7.png)
[latest.log](https://github.com/pWn3d1337/Techguns2/files/2466340/latest.log)
[Uploading debug.log…]()
