### ISSUE TITLE
Dual wield bug for non-dual-wield-able weapons

### ISSUE THREAD

**Issue by CKTheUltimate** [pWn3d1337/Techguns2#7]
Currently dual wield only works for all pistols and PDW ,when dual-wielding other weapons,they become invisible on the left hand.
Some weapons may rely on right-click for aiming(like the bolt-action rifle),but other than those scoped weapons,others should be dual-wield-able.

**Comment by pWn3d1337** [comment]
No they should not. They are two-handed weapons and you can't dual wield them. Two handed weapons can only be used in the main hand.

**Comment by CKTheUltimate** [comment]
Thanks for replying to my idea,and sorry for coming up with some weird ideas sometimes.I thought that dual-wield AK would be cool and tried posting here,but maybe it is just something not practical...
