### ISSUE TITLE
[Question] How to remove Chemical Lab recipes using CraftTweaker

### ISSUE THREAD

**Issue by lordfriend** [pWn3d1337/Techguns2#72]
After search the code, old Techguns wiki. I can only add a new recipe to Chemical Lab. 
By add this line I can added a new recipe to fill the fuel tank with gasoline.
`mods.techguns.ChemLab.addRecipe(<techguns:itemshared:28>, 1, <minecraft:dirt>, 0, <liquid:gasoline> * 2500, false, <techguns:itemshared:27>, <liquid:water> * 0, 100);`

if I want to remove the original biodiesel version fuel tank recipes the following code doesn't work. even I remove any other add chemical lab recipe codes.
`mods.techguns.ChemLab.removeRecipe(<techguns:itemshared:27>, null);`
neither this:
`mods.techguns.ChemLab.removeRecipe(<techguns:itemshared:27> * 1, null);`

**Comment by pWn3d1337** [comment]
Exactly that. This will be fixed in the next version, but I don't know when that is.

**Comment by lordfriend** [comment]
So currently the only thing I can do is totally disable chemical lab by removing the craft table recipe of chemical lab block.

**Comment by wormzjl** [comment]
Is it possible to push a hotfix for this instead of everything else?

**Comment by lordfriend** [comment]
@wormzjl If you have knowledge of Java, it's not too hard to fix this from source code. Since it seems the author of the mod is not very actively updating. I don't worry about compatibility with future versison.
I made two forks which may help you
One is only fixing dependency and FTB compatibility. So you can compile without issue and be able to use with the latest version of FTB lib and FTB utilities.

https://github.com/lordfriend/Techguns2/tree/dependencies_fix

The other one make future modification. like add super mutant to The End to make player harder to kill the dragon and nerf the jetpack in overworld/Neither/The End. Besides, add fluid configuration for chemical.

https://github.com/lordfriend/Techguns2/tree/my-server-enhance

Feel free to fork from any branch if it is helpful.

**Comment by wormzjl** [comment]
The author is still around, we shall wait.
If you have fixed something, IMO it's better to make a PR here.

**Comment by pWn3d1337** [comment]
I'm still around and I want to make a new release with bug fixes soon. @lordfriend if you make a pr to the fluid list from config file I'm going to merge that.

I have already updated the buildscript and code to new FTBlib.

**Comment by lordfriend** [comment]
OK, I've made a PR.
