### ISSUE TITLE
Spawnrates for these mobs in the nether are broken.

### ISSUE THREAD

**Issue by TheUnderTaker11** [pWn3d1337/Techguns2#75]
What title says. These guys all spawn with machine guns and shit, and there are always a billion of them in the nether. Hell it's hard to even find any normal pigman, about 95% of the mobs spawned outside of nether fortresses are nothing but this mod.            
Seems like an abandoned mod though, since the NBT bug "fixed" February still isn't fixed.

**Comment by pWn3d1337** [comment]
Change spawnweights in config.

And it is fixed: https://github.com/pWn3d1337/Techguns2/releases

**Comment by TheUnderTaker11** [comment]
Thanks, was not aware it was a config option. Why is the fix not on curseforge then?
