### ISSUE TITLE
[1.12] Reaction chamber containing fluid breaks other mods rendering

### ISSUE THREAD

**Issue by wormzjl** [pWn3d1337/Techguns2#77]
With fluid
![image](https://user-images.githubusercontent.com/2989009/50483463-41a86e80-09ec-11e9-8d6f-213344cf34c4.png)

Without fluid
![image](https://user-images.githubusercontent.com/2989009/50483488-5ab11f80-09ec-11e9-8514-b0b0bef0eec0.png)

Also I'm getting a lot of console spams like this:
 [STDOUT]: [techguns.client.render.tileentities.RenderReactionChamber:drawFluidCubeWithTesselator:231]: Height:0.29375 MH:2.9375

I don't have Eleccore

**Comment by pWn3d1337** [comment]
are you on 1.7.10 or 1.12?

**Comment by wormzjl** [comment]
I'm on 1.12
