### ISSUE TITLE
[Suggestion] Config option to force disable weapon block damage

### ISSUE THREAD

**Issue by wormzjl** [pWn3d1337/Techguns2#78]
This could be a life saver for server admins.

**Comment by Fishkaras** [comment]
Use config\techguns.cfg file to configure block damage:

    # Highest blockHardness advanced explosive charges can break, obsidian is 50.0) [range: 0.0 ~ 3.4028235E38, default: 100.0]
    S:ExplosiveChargeAdvancedMaxHardness=0.0

    # Highest blockHardness normal explosive charges can break, obsidian is 50.0) [range: 0.0 ~ 3.4028235E38, default: 30.0]
    S:ExplosiveChargeMaxHardness=0.0

**Comment by wormzjl** [comment]
It seems that this is for explosive charges, but I'm referring to weapons like the BFG

**Comment by pWn3d1337** [comment]
This has already been built in dev version. 

boolean that only allows opped players to use unsafe mode.
https://github.com/pWn3d1337/Techguns2/blob/master/src/main/java/techguns/TGConfig.java#L113

**Comment by wormzjl** [comment]
awesome
