### ISSUE TITLE
Monster drops have empty NBT-tags

### ISSUE THREAD

**Issue by pWn3d1337** [pWn3d1337/Techguns2#8]
> The items dropped by the mobs have empty NBT tags and this prevents them from stacking from normal items. Examples are coal and iron ingots.

https://github.com/pWn3d1337/Techguns/issues/122

**Comment by mjjOpencode2015** [comment]
Submit bug:
Reaction Chamber make Anti Gravity Core only causes explosions.Has been tested many times.

Please forgive me for my bad English.

**Comment by SteamDoge9000** [comment]
I have the issue too
and its still occurring on the latest version (1.12.2)
it mostly come from zombie miners if I can recall.

**Comment by pWn3d1337** [comment]
The newest test releases have this fixed: https://github.com/pWn3d1337/Techguns2/releases
