### ISSUE TITLE
[1.12.2] Unexpected crash

### ISSUE THREAD

**Issue by HydrogenC** [pWn3d1337/Techguns2#86]
Crash while starting up. 
[crash-2019-01-12_18.55.25-client.txt](https://github.com/pWn3d1337/Techguns2/files/2764066/crash-2019-01-12_18.55.25-client.txt)

**Comment by pWn3d1337** [comment]
Update forge version, newest version is on Curseforge (Techguns 2.0.1.2) and has required forge version listed as 2807
