### ISSUE TITLE
Cannot use crafttweaker to set the maximum stack size of techgun items?

### ISSUE THREAD

**Issue by wormzjl** [pWn3d1337/Techguns2#89]
For reference: https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Items/IItemStack/#maximum-stack-size

Such functions works well for other mods, but does not work on techguns items.
My guess is that there is some sort of system in TG that overrides original method?

I have the following script:
```
val coil = <techguns:itemshared:68>;
coil.maxStackSize = 1;

val motor = <techguns:itemshared:70>;
motor.maxStackSize = 1;

```

**Comment by pWn3d1337** [comment]
Shared item is an item where many items get compressed into 1 item (saving item ids). Shared item overrides getMaxStackSize and therefore it is not be possible to change the maxStackSize.

**Comment by wormzjl** [comment]
Normally I think one can set the stack size for each meta?

**Comment by liach** [comment]
Another mod is needed to tweak the internal data that defines each of the shared item. https://github.com/pWn3d1337/Techguns2/blob/36464909c4f096dfa5ec7a5be282234d3b828365/src/main/java/techguns/items/GenericItemShared.java#L67
