### ISSUE TITLE
No Drops from Mobs?

### ISSUE THREAD

**Issue by system-operator** [pWn3d1337/Techguns2#90]
forge-1.12.2-14.23.5.2768-universal.jar
spongeforge-1.12.2-2768-7.1.5-RC3515.jar
techguns-1.12.2-2.0.1.1.jar

It appears with the latest Curseforge version, and latest stable SpongeForge, none of the Zombie Miners and other random mobs are dropping any loot?

Suggestions? Common working bug?

**Comment by pWn3d1337** [comment]
You don't use the latest techguns version. The sponge incompatibility has been fixed.
