### ISSUE TITLE
[Sponge]Power Armor extra health glitch

### ISSUE THREAD

**Issue by Fishkaras** [pWn3d1337/Techguns2#93]
Minecraft version: 1.12.2
Forge version: 2808
Sponge version: spongeforge-1.12.2-2768-7.1.4
Techguns: 2.0.1.3_pre1

Screenshots:
https://i.imgur.com/MUjP1yd.png

https://i.imgur.com/85ejCxq.png

Description:
Armor adds 5 points of health: 3 hearts in GUI, 2.5 of them are filled.
If a sponge is installed, 5 hearts are displayed, 2.5 of them are filled.
At the same time the last 2 hearts constantly flicker
But this flicker can not be seen in the screenshot.

**Comment by pWn3d1337** [comment]
This seems like sponge's fault

**Comment by Fishkaras** [comment]
Fixed:
https://github.com/SpongePowered/SpongeForge/issues/2588

**Comment by pWn3d1337** [comment]
Wasn't a techguns issue anyway.
