### ISSUE TITLE
2.0.1.2_1 breaks Immersive Railroading's rendering

### ISSUE THREAD

**Issue by BrisingrAerowing** [pWn3d1337/Techguns2#94]
With Techguns:
![2019-01-25_18 37 22](https://user-images.githubusercontent.com/250409/51779230-16d93500-20d4-11e9-8d11-2796fc45e50c.png)

Without:
![2019-01-25_19 01 39](https://user-images.githubusercontent.com/250409/51779236-1d67ac80-20d4-11e9-97ec-5450515e29f2.png)

As you can see, the rendering is a bit broken, as the track blueprint is barely visible with the mod. I was next to a military compound, FWIW (I actually spawned in it).

**Comment by pWn3d1337** [comment]
In a quick test I can't reproduce the error.

**Comment by pWn3d1337** [comment]
tested again next to a military base, no problems visible.

**Comment by BrisingrAerowing** [comment]
I'll do some more testing.

**Comment by HydrogenC** [comment]
I’ve tested and found that there are no conflicts with these mods, IR’s rendering isn’t affected by TG.

**Comment by BrisingrAerowing** [comment]
I've rebuilt my pack completely and can't replicate this anymore. It was probably a multiple mod conflict issue (I hate those as they take so \[BEEP\] long to figure out, especially in larger packs).
