### ISSUE TITLE
Turret ID

### ISSUE THREAD

**Issue by horosgrisa** [pWn3d1337/Techguns2#96]
I use Techguns within epicsiegemod but it modify AI of NPC. It's bad when NPC can't move like turret. I try to blacklist turret from AI modification but no one of following id didn't match:
```
        techguns.blocks.machines.BasicMachine
        BasicMachine
        basic_machine
        techguns.entities.npcs.NPCTurret
        NPCTurret
        techguns:basicmachine
        techguns:basicmachine_3_turret
        basicmachine_3_turret
```
What is correct id of turret?

**Comment by pWn3d1337** [comment]
the turret entity npc is registered as (Registry Name)
`techguns:turret`

**Comment by horosgrisa** [comment]
It works!!! Thank you very much.
