### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by HydrogenC** [pWn3d1337/Techguns2#99]
I entered my map then the game crashed. 
CR: [crash-2019-02-11_19.37.46-client.txt](https://github.com/pWn3d1337/Techguns2/files/2850875/crash-2019-02-11_19.37.46-client.txt)
Also, before the crash, I noticed that the connection of the TE wires are broken as the image shown. 
[2019-02-11_19 47 04](https://user-images.githubusercontent.com/33123710/52561305-fc25f080-2e35-11e9-83bf-795bc893d120.png)

**Comment by HydrogenC** [comment]
The wire issue only happen to wires inside the chunk that contains a techguns charger I placed.

**Comment by HydrogenC** [comment]
My java version is 8u201, incompatible with new java versions?

**Comment by pWn3d1337** [comment]
I do think your installation or map is damaged or something. This error should not happen.
